# Generated by Django 2.1.7 on 2019-05-01 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_auto_20190501_0810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasklist',
            old_name='competed_pro',
            new_name='archive_project',
        ),
    ]
