# Generated by Django 2.1.7 on 2019-05-01 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_auto_20190501_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
